services:
  # Admin Application
  admin-app:
    build: .
    container_name: exadmin-admin-app
    ports:
      - "8080:8080"
    environment:
      # Database
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      
      # Redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      
      # Application
      SPRING_PROFILES_ACTIVE: prod
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      
      # Email
      GMAIL_USERNAME: ${GMAIL_USERNAME}
      GMAIL_APP_PASSWORD: ${GMAIL_APP_PASSWORD}
      
      # Exchange API
      EXCHANGE_API_KEY: ${EXCHANGE_API_KEY}
      
      # AWS S3
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
    external_links:
      - shared-redis:redis
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    networks:
      - exadmin-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s


volumes:
  uploads:
  logs:

networks:
  exadmin-network:
    driver: bridge
