spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}  # 기본값: local

# 공통 설정 (모든 환경에서 공유)
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.example.domain

# Spring Boot 기본 에러 페이지 비활성화
mvc:
  throw-exception-if-no-handler-found: true
web:
  resources:
    add-mappings: false
# 에러 페이지 완전 비활성화
error:
  whitelabel:
    enabled: false 