name: Deploy to EC2

on:
  push:
    branches: [ master ]
  workflow_dispatch:  # 수동 실행 가능

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa
        ssh-add -l
        
    - name: Add EC2 to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts || true
        chmod 600 ~/.ssh/known_hosts
        
    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
          echo "현재 실행 중인 프로세스 중지..." &&
          pkill -f exProject || true &&
          echo "프로젝트 클론/업데이트..." &&
          if [ -d "exchange_rate_admin" ]; then
            cd exchange_rate_admin && git pull origin master
          else
            git clone https://github.com/${{ github.repository }}.git exchange_rate_admin && cd exchange_rate_admin
          fi &&
          echo "애플리케이션 빌드..." &&
          ./gradlew clean build -x test &&
          echo "애플리케이션 실행..." &&
          nohup java -jar build/libs/exProject-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
          echo "배포 완료!" &&
          sleep 3 &&
          ps aux | grep exProject | grep -v grep
        '
        
    - name: Check deployment status
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
          echo "애플리케이션 상태 확인..." &&
          curl -f http://localhost:8080/health || echo "헬스체크 실패" &&
          echo "로그 확인 (최근 10줄)..." &&
          tail -10 exchange_rate_admin/app.log
        '
