name: Deploy to EC2

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy application
        run: |
          ssh -i ~/.ssh/id_rsa \
              -o ConnectTimeout=60 \
              -o ServerAliveInterval=30 \
              -o ServerAliveCountMax=3 \
              -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          echo "=== 배포 시작 ==="
          
          if pgrep -f exProject > /dev/null; then
            echo "실행 중인 프로세스 발견, 종료 중..."
            pkill -f exProject
            sleep 2
          else
            echo "실행 중인 프로세스 없음"
          fi
          
          if [ -d "exchange_rate_admin" ]; then
            cd exchange_rate_admin
            git pull origin master
          else
            git clone https://github.com/${{ github.repository }}.git exchange_rate_admin
            cd exchange_rate_admin
          fi
          
          ./gradlew clean build -x test
          
          # 환경변수 직접 설정
          export DB_URL="jdbc:mysql://exchange-rate.cx4u82sc0s99.ap-northeast-2.rds.amazonaws.com:3306/exchange_rate?useSSL=false&allowPublicKeyRetrieval=true"
          export DB_USERNAME="${{ secrets.DB_USERNAME }}"
          export DB_PASSWORD="${{ secrets.DB_PASSWORD }}"
          export REDIS_HOST="${{ secrets.REDIS_HOST }}"
          export REDIS_PORT="${{ secrets.REDIS_PORT }}"
          export GMAIL_USERNAME="${{ secrets.GMAIL_USERNAME }}"
          export GMAIL_APP_PASSWORD="${{ secrets.GMAIL_APP_PASSWORD }}"
          export EXCHANGE_API_KEY="${{ secrets.EXCHANGE_API_KEY }}"
          export S3_BUCKET_NAME="${{ secrets.S3_BUCKET_NAME }}"
          export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
          export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          export AWS_REGION="${{ secrets.AWS_REGION }}"
          export SPRING_PROFILES_ACTIVE="prod"
          
          # 환경변수 파일도 생성 (백업용)
          echo "DB_URL=$DB_URL" > ~/.env
          echo "DB_USERNAME=$DB_USERNAME" >> ~/.env
          echo "DB_PASSWORD=$DB_PASSWORD" >> ~/.env
          echo "REDIS_HOST=$REDIS_HOST" >> ~/.env
          echo "REDIS_PORT=$REDIS_PORT" >> ~/.env
          echo "GMAIL_USERNAME=$GMAIL_USERNAME" >> ~/.env
          echo "GMAIL_APP_PASSWORD=$GMAIL_APP_PASSWORD" >> ~/.env
          echo "EXCHANGE_API_KEY=$EXCHANGE_API_KEY" >> ~/.env
          echo "S3_BUCKET_NAME=$S3_BUCKET_NAME" >> ~/.env
          echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> ~/.env
          echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> ~/.env
          echo "AWS_REGION=$AWS_REGION" >> ~/.env
          echo "SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE" >> ~/.env
          
          # 환경변수 확인
          echo "=== 환경변수 확인 ==="
          echo "DB_URL: $DB_URL"
          echo "DB_USERNAME: $DB_USERNAME"
          echo "DB_PASSWORD: [HIDDEN]"
          echo "REDIS_HOST: $REDIS_HOST"
          echo "REDIS_PORT: $REDIS_PORT"
          echo "SPRING_PROFILES_ACTIVE: $SPRING_PROFILES_ACTIVE"
          
          nohup java -jar build/libs/exProject-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod > app.log 2>&1 &
          
          sleep 15
          
          echo "=== 배포 완료 ==="
          ps aux | grep exProject | grep -v grep || echo "프로세스 없음"
          netstat -tlnp | grep :8080 || echo "포트 8080이 열려있지 않음"
          tail -30 app.log
          EOF
