name: Deploy to EC2

on:
  push:
    branches: [ master ]
  workflow_dispatch:  # 수동 실행 가능

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        # SSH 키 저장 (줄바꿈 복원)
        echo -e "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        chmod 700 ~/.ssh
        echo "SSH 키 설정 완료"
        ls -la ~/.ssh/
        echo "SSH 키 형식 확인:"
        head -1 ~/.ssh/id_rsa
        tail -1 ~/.ssh/id_rsa
        
    - name: Add EC2 to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts || true
        chmod 600 ~/.ssh/known_hosts
        
    - name: Test SSH connection
      run: |
        echo "SSH 연결 테스트 시작..."
        echo "Host: ${{ secrets.EC2_HOST }}"
        echo "User: ${{ secrets.EC2_USER }}"
        echo "SSH 키 파일 확인:"
        ls -la ~/.ssh/id_rsa
        echo "SSH 연결 테스트:"
        ssh -i ~/.ssh/id_rsa -o ConnectTimeout=30 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'echo "SSH 연결 성공!"'
        
    - name: Stop existing process
      run: |
        ssh -i ~/.ssh/id_rsa -o ConnectTimeout=30 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'pkill -f exProject || true'
        
    - name: Clone/Update repository
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
          echo "프로젝트 클론/업데이트..." &&
          if [ -d "exchange_rate_admin" ]; then
            cd exchange_rate_admin && git pull origin master
          else
            git clone https://github.com/${{ github.repository }}.git exchange_rate_admin && cd exchange_rate_admin
          fi
        '
        
    - name: Build application
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
          cd exchange_rate_admin &&
          echo "애플리케이션 빌드..." &&
          ./gradlew clean build -x test
        '
        
    - name: Start application
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
          cd exchange_rate_admin &&
          echo "애플리케이션 실행..." &&
          nohup java -jar build/libs/exProject-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
          echo "배포 완료!"
        '
        
    - name: Check deployment status
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
          echo "애플리케이션 상태 확인..." &&
          curl -f http://localhost:8080/health || echo "헬스체크 실패" &&
          echo "로그 확인 (최근 10줄)..." &&
          tail -10 exchange_rate_admin/app.log
        '
