name: Deploy to EC2

on:
  push:
    branches: [ master ]
  workflow_dispatch:  # 수동 실행 가능

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup SSH
      run: |
        echo "${{ secrets.EC2_PRIVATE_KEY }}" > private_key.pem
        chmod 600 private_key.pem
        eval "$(ssh-agent -s)"
        ssh-add private_key.pem
        
    - name: Add EC2 to known hosts
      run: |
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
        
    - name: Deploy to EC2
      run: |
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
          cd exAdmin &&
          echo "현재 실행 중인 프로세스 중지..." &&
          pkill -f exProject || true &&
          echo "Git에서 최신 코드 받기..." &&
          git pull origin main &&
          echo "애플리케이션 빌드..." &&
          ./gradlew clean build -x test &&
          echo "애플리케이션 실행..." &&
          nohup java -jar build/libs/exProject-0.0.1-SNAPSHOT.jar > app.log 2>&1 & &&
          echo "배포 완료!" &&
          sleep 3 &&
          ps aux | grep exProject | grep -v grep
        '
        
    - name: Check deployment status
      run: |
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
          echo "애플리케이션 상태 확인..." &&
          curl -f http://localhost:8080/health || echo "헬스체크 실패" &&
          echo "로그 확인 (최근 10줄)..." &&
          tail -10 exAdmin/app.log
        '
